# Generated by Django 3.2.9 on 2021-11-03 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211103_1815'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
