# Generated by Django 3.2.9 on 2021-11-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211104_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='no-avatar.png', upload_to='users/avatars/', verbose_name='аватар'),
        ),
    ]
